import type { Metadata } from "next";
import Link from "next/link";
import PrelineScriptWrapper from "@/components/PrelineScriptWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta charSet="UTF-8" />
      </head>
      <body>
        <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-100">
            <header className="w-full bg-gradient-to-r fixed from-blue-700 via-blue-500 to-blue-400 shadow">
            <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
              <Link href="/" className="flex items-center">
              <span
                className="text-2xl font-extrabold tracking-tight text-white drop-shadow-md"
                style={{ fontFamily: "'Geist', 'Segoe UI', Arial, sans-serif" }}
              >
                Job
                <span className="text-blue-200">seeker</span>
              </span>
              </Link>
              <Link
              href="/login"
              className="ml-4 px-4 py-2 rounded text-sm bg-white text-blue-700 font-semibold shadow hover:bg-blue-50 transition"
              >
              Prihlásiť sa
              </Link>
            </div>
            </header>
          <main className="flex px-2 flex-col items-center min-h-screen pt-20">
                    {children}

          </main>
    </div>
                <PrelineScriptWrapper />

      </body>

    </html>
  );
}
